### ISSUE TITLE
Error code 64

### ISSUE THREAD

**Issue by Rutger-Knijnenburg** [juliansangillo/tag-version#1]
First of all, big thanks for publishing this Github Action!

I'm trying to implement this in my repository. I'm commiting the yml file directly into master.
I'm using the default flow:

```
      - name: Checkout
        uses: actions/checkout@v2  
        with:  
          fetch-depth: 0

      - name: Version
        id: version  
        uses: juliansangillo/tag-version@v1.5
        with:  
          production-branch: master  
          test-branch: test  
          dev-branch: develop  
```

However, it gives me the 64 error (A 'latest' tag doesn't exist when pulling commits into test or production.). How to solve this? Obviously, my repository isn't tagged yet. I can't seem to find how to create the initial tag in your readme.

Thanks in advance!
